### ISSUE TITLE
Crash in MC 1.16.3

### ISSUE THREAD

**Issue by K0-RR** [ethanejohnsons/FPV-Racing-Mod-Fabric#14]
Generates 3 crash reports - https://hatebin.com/dqcikqcozs https://hatebin.com/kumhvigkrr https://hatebin.com/ghzvqzwyil

**Comment by ethanejohnsons** [comment]
It would appear you were using MultiMC which wasn't compatible at that time. It is now as of the [latest release](https://github.com/LazuriteMC/FPV-Racing-Mod-Fabric/releases/tag/mc1.16.3-0.1.3). Let me know if that resolves your issue.
