### ISSUE TITLE
Build from source throws an error

### ISSUE THREAD

**Issue by Ahptt** [ethanejohnsons/FPV-Racing-Mod-Fabric#27]
When I git clone and then gradle build, I get the following output. 

`> Configure project :
Fabric Loom: 0.10.66

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ahpt/Documents/Git/Quadz-development/build.gradle' line: 72

* What went wrong:
A problem occurred evaluating root project 'quadz'.
> Could not get unknown property 'publish.lazurite.alias' for root project 'quadz' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 676ms`

I am still quite new to building from source, so please educate me if there is something that I am doing incorrectly. Thank you!

**Comment by The-PPWD** [comment]
Fixed in d32e4882e4242ace48cba20828a4f57164dbc285
